version: "3.7"
services:
    nginx:
      container_name: bbs-nginx
      build:
        context: ./nginx/
        dockerfile: Dockerfile
      ports:
        - 8080:80
      volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      links:
        - front
        - back
        - postgres
    front:
      container_name: bbs-front
      build:
        context: ./front/
        dockerfile: Dockerfile
      volumes:
      - "./front/src:/var/bbs/front/src"
      ports:
        - 8181:8080
    back:
      container_name: bbs-back
      build: 
        context: ./back/
        dockerfile: ./Dockerfile
      ports:
        - 8282:8080
      links:
        - postgres
    postgres:
      container_name: bbs-postgres
      build: ./postgres/
      ports:
        - 6543:5432